### ISSUE TITLE
It does nothing (or "i i is undefined")

### ISSUE THREAD

**Issue by valignatev** [TheBB/evil-indent-plus#3]
Hi! I try to use this awesome library but can't do anything with indented text objects for some reason.

First of all, it is installed, and all its functions are available (for example, `evil-indent-plus-i-indent` `-a-indent` and so on). But when I try to use shortcuts, for example, select indented region with `vii`, minibuffer says `i i is undefined`. If I call function directly with M-x, nothing happens. 
I've installed it with use package like this:
```
(use-package evil
  :ensure t
  :config
  (evil-mode 1)

  (use-package evil-indent-plus
    :ensure t))
```
if it'll help.

**Comment by TheBB** [comment]
This package doesn't define any keybindings on its own. Please see the readme.

**Comment by valignatev** [comment]
That's because I'm stupid. -_- Thanks a lot!
